from enum import Enum, auto

class VBCObjectType(Enum):
    """
    类与对象类型
    """
    CUSTOM = "custom"
    VOID = "void"
    CLASS = "class"
    CHAR = "char"
    SHORT = "short"
    INT = "int"
    LONG = "long"
    LONGLONG = "long long"
    NLINT = "unlimited int"
    FLOAT = "float"
    DOUBLE = "double"
    NLFLOAT = "unlimited float"
    BOOL = "bool"
    NULL = "null"
    POINTER = "pointer"
    LIST = "list"
    MAP = "map"
    MODULE = "module"
    STRING = "string"
    FUNCTION = "function"
    NATIVE_FUNCTION = "native_function"
    INSTANCE = "instance"
    RANGE = "range"
